### ISSUE TITLE
Ts/Tv ratio calculation

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/vcf.iobio.io#17]
I generated a vcf file that only contains indels and opened it in vcf.iobio. As expected, the base changes window is empty, since there are no SNPs, so no base changes to show. However, the Ts/Tv ratio is 1.20. I am confused as to how there is a value here (and bars showing the relative numbers of transitions and transversions), when there are no SNPs from which to calculate the values.

**Comment by tonydisera** [comment]
SnpSift TSTV calculations on my genome:
  chr1 = 1.954
  chr1 indels =  (no results, as expected)

But in vcf.iobio:
  chr1 =

**Comment by tonydisera** [comment]
When I run vcftools, the tstv ratio tracks with vcfstatsalive:

bash-3.2#  tabix -h ~/Documents/michigan_genome/Sample13_combined_filtered_normalized.vcf.gz 1 | ./vcf-tstv
**1.51**	359126	(ts=216157 tv=142969 total=416888 skipped=57762 multiallelic=392)
bash-3.2#

**Comment by AlistairNWard** [comment]
I think the norm is to count based on alleles, not genotypes, so a single count for each variant.

**Comment by tonydisera** [comment]
Great.  Based on the calculations coming back from vcftools, vcfstatsalive is calculating the tstv ratio correctly.  I made a small fix to vcfstatsalive to only evaluating SNPs.  Once this is deployed to iobio, this bug can be closed.

**Comment by tonydisera** [comment]
The counts are slightly different between vcfstatsalive and vcftools.  

[tstv_vcfstatsalive_vs_vcftools.xlsx](https://github.com/tonydisera/vcf.iobio.io/files/292052/tstv_vcfstatsalive_vs_vcftools.xlsx)

**Comment by tonydisera** [comment]
I've pushed the fixes to vcfstatsalive and asked Yi to deploy them to prod iobio services.
