### ISSUE TITLE
Indication when data isn't present

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/vcf.iobio.io#18]
We need to include an indication of why charts are empty, in the case that they are. For example:

1. No QUAL info in file -> empty variant quality plot
2. No INFO field (e.g. it is a '.') or no AF info in the INFO field -> No AF plot
3. Indels only VCF -> Should have no Ts/Tv and no base change plot
4. SNPs only VCF -> No indel length plot.

**Comment by tonydisera** [comment]
The code now checks for existence of non-zero values.  When values are not present, the chart panel will show 'no values present'.

<img width="1188" alt="screenshot 2016-05-31 13 24 59" src="https://cloud.githubusercontent.com/assets/8420103/15687660/1ba6af92-2733-11e6-8deb-2765af7b7c9c.png">
