### ISSUE TITLE
File not loading

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/vcf.iobio.io#19]
EVA have some files that don't load. I've put them on AWS so they can be checked at:

http://vcf.iobio.io/?vcf=http://s3.amazonaws.com/iobio/eva_test/genomedk.chrY.gatk_indels.r1.EVA.NOT_LOADING.vcf.gz

http://vcf.iobio.io/?vcf=http://s3.amazonaws.com/iobio/eva_test/genomedk.chr22.gatk_indels.r1.EVA.NOT_LOADING.vcf.gz

**Comment by AlistairNWard** [comment]
Modified file locations:

http://vcf.iobio.io/?vcf=https://s3.amazonaws.com/iobio/app_testing/vcf_files/fails_to_load.vcf.gz

http://vcf.iobio.io/?vcf=https://s3.amazonaws.com/iobio/app_testing/vcf_files/fails_to_load_2.vcf.gz

http://vcf.iobio.io/?vcf=https://s3.amazonaws.com/iobio/app_testing/vcf_files/fails_to_load_3.vcf.gz

**Comment by AlistairNWard** [comment]
http://vcf.iobio.io/?vcf=https://s3.amazonaws.com/iobio/app_testing/vcf_files/fails_to_load.vcf.gz

Loads fine, but there is something odd with the indel distribution (the x axis appears to be missing).

http://vcf.iobio.io/?vcf=https://s3.amazonaws.com/iobio/app_testing/vcf_files/fails_to_load_2.vcf.gz

Only contains chromosome 22, fails to load and is riddled with errors.

http://vcf.iobio.io/?vcf=https://s3.amazonaws.com/iobio/app_testing/vcf_files/fails_to_load_3.vcf.gz

Only contains chromosome Y, fails to load and is riddled with errors.

**Comment by AlistairNWard** [comment]
![screen shot 2016-06-10 at 9 48 37 am](https://cloud.githubusercontent.com/assets/523111/15970253/f7c2cfc8-2ef0-11e6-92e1-3f3a7ee5b38c.png)

**Comment by AlistairNWard** [comment]
Just handle the image problem. Second two files moved to #31

**Comment by tonydisera** [comment]
I've migrated the chart over to Chase's iobio.viz bar chart object so that outliers can be ignored.  The chart is still quite difficult to read.
<img width="1043" alt="screenshot 2016-06-10 10 32 02" src="https://cloud.githubusercontent.com/assets/8420103/15983074/297812e0-2f59-11e6-8974-5a3529ef9ba7.png">

**Comment by AlistairNWard** [comment]
Looks way better to me. We seem to be using a lot more vertical space for the barViewer than used in bam.iobio. Is it possible to make this a bit smaller?

I'm also seeing an error in the console regarding reading the index. Is this something real?

Uncaught ReferenceError: ignoreErrorMessage is not defined
vcf.iobio.js:1024 tabix Error: stderr - Could not load .tbi/.csi index of https://s3.amazonaws.com/iobio/app_testing/vcf_files/fails_to_load.vcf.gz

vcf.iobio.js:1024 tabix Error: prog process exited with code 1

**Comment by tonydisera** [comment]
Thanks for the feedback!  Better? 

<img width="1253" alt="screenshot 2016-06-15 08 16 01" src="https://cloud.githubusercontent.com/assets/8420103/16083231/7f7e3784-32d1-11e6-888e-1b1ba5aaf35c.png">

**Comment by AlistairNWard** [comment]
I'm happy with it. If we could make the top panel in the 'Insertion & Deletion Lengths' take up more vertical space and squeeze them together a bit more, I don't think that would be a bad thing, but if that can't be done, I'm happy for this to be closed.

**Comment by tonydisera** [comment]
Yeah, this is probably the best I can do for now.  Otherwise, it is hard to select the bounding rectagle on the bottom chart.
