### ISSUE TITLE
Variant density dropoff shown as slope for genome (all references) view.

### ISSUE THREAD

**Issue by tonydisera** [tonydisera/vcf.iobio.io#27]
<img width="1394" alt="screenshot 2016-06-03 11 21 37" src="https://cloud.githubusercontent.com/assets/8420103/15787088/81c70c3a-297d-11e6-95f4-ff6b6a1679c5.png">

**Comment by tonydisera** [comment]
use test file: https://s3.amazonaws.com/iobio/app_testing/vcf_files/no_af_indels_qual.vcf.gz

**Comment by AlistairNWard** [comment]
Not sure if this is the same problem or not, but there is something odd going on around chr20-23. There is a line being drawn behind the density.

Also, are we happy with just numerical values for all chromosomes? For the human genome, we are going to want to see X and Y, not 23 and 24.

**Comment by tonydisera** [comment]
Taking a closer look at the density data, there is something strange going on with chr 20.  The density data has points through ~ 130,500,000, but the chromosome is only 63,000,000.    I wonder if the index needs to be re-generated for this file or if we are perhaps seeing the problem of an out-dated index file....
