### ISSUE TITLE
Reference length error

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/vcf.iobio.io#28]
Tried running a public 10X vcf file and it failed citing that vcf.iobio couldn't get the reference sequence lengths and set them all to zero. Looking at the vcf file, there doesn't seem to be any obvious reason why this would fail. It seems that this error is only occuring when pulling the vcf from the 10X S3 bucket or as a local file. I uploaded the vcf to app_testing (https://s3.amazonaws.com/iobio/app_testing/vcf_files/NA12878_10X.vcf.gz) and this seems to work, except for the ordering of the chromosomes.

URL to our S3 bucket:

<img width="1420" alt="screen shot 2016-06-07 at 5 38 43 pm" src="https://cloud.githubusercontent.com/assets/523111/15879197/b0bf83c6-2cd6-11e6-930a-8386598979b1.png">

From local file:

<img width="1424" alt="screen shot 2016-06-07 at 5 39 37 pm" src="https://cloud.githubusercontent.com/assets/523111/15879206/cfebc372-2cd6-11e6-8c48-b24bec2976cd.png">

**Comment by tonydisera** [comment]
I'm taking a look at this now.

**Comment by tonydisera** [comment]
My first thought is that the original S3 location doesn't have the vcf.gz.tbi in the same directory or it is not set to public access.

**Comment by tonydisera** [comment]
I can reproduce the problem with the local file.  I'm debugging the problem now.
