### ISSUE TITLE
Error with filenames should be handled

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/vcf.iobio.io#30]
Use this file and the index name is not the same as the vcf filename:

http://vcf.iobio.io/?vcf=https://s3-us-west-2.amazonaws.com/10x.files/samples/genome/NA12878_WGS/NA12878_WGS_phased_variants.vcf.gz

**Comment by tonydisera** [comment]
From @chmille4  
here's the error when there is no .tbi file:
open: No such file or directory
[main] fail to open the data file.

**Comment by tonydisera** [comment]
You can also try with our vcf files:
http://s3.amazonaws.com/iobio/app_testing/vcf_files/wrong_tbi.vcf.gz

**Comment by tonydisera** [comment]
Fixed for both local files and URLs.
