### ISSUE TITLE
Filtering on samples doesn't seem to work

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/vcf.iobio.io#37]
1. The cross out to quit the filter samples doesn't work, you have to just click elsewhere on the screen to dismiss the filter samples box (if you decide you don't want to filter - so don't want to press load).

2. The drop down box seems to be wider than the modal, and I can't get it to do anything. Certainly can't get any sample names in.

**Comment by tonydisera** [comment]
You found another good one, Al!  Thank you.  Way back in Nov 2016, a commit some lines of code in init() that was initializing the sample dropdown.  It was probably a merge conflict with genome build that I resolved incorrectly.  You rock.

This is now fixed on production.

**Comment by AlistairNWard** [comment]
The formatting is fixed, but I selected a subset of samples and it didn't seem to have any effect on the results. Is the filtering actually working?

**Comment by tonydisera** [comment]
Hmm...  Let me look at this.

**Comment by tonydisera** [comment]
Fixed!
