### ISSUE TITLE
Specifying tbi index URL stopped working

### ISSUE THREAD

**Issue by MariaNattestad** [tonydisera/vcf.iobio.io#58]
Both through the UI and by inserting "&tbi=..." in the URL. It used to work to specify the TBI index URL about a month or two ago, but now it doesn't work anymore. This is necessary for fast linking from DNAnexus. Thanks for your help!

**Comment by tonydisera** [comment]
Thanks Maria.  I am looking into this right now.

**Comment by tonydisera** [comment]
I located the problem with the shell script in production.  We will deploy this fix to production and let you know when the fix is in place.  Thank you for pointing this out!

**Comment by MariaNattestad** [comment]
Thank you so much for the quick fix! By the way, you should know that vcf iobio is now available as a viewer on the DNAnexus platform, so our users have easy access to it. Thanks for making it so great and easy to link to with file URLs! 
(Also, Darren says hi.)

**Comment by tonydisera** [comment]
This should be fixed now.  Please let us know if you run into any troubles.
Hi back to Darren!!

**Comment by MariaNattestad** [comment]
It is working perfectly now, thank you so much!

**Comment by MariaNattestad** [comment]
Hi Tony
I am seeing this exact same problem again where the TBI index stopped working. Did you revert to an earlier version in production?
Thanks!
Maria

**Comment by tonydisera** [comment]
Oh dear.  My apologies, Maria.  I will look into this.  
Tony

**Comment by tonydisera** [comment]
Hi Maria -
We had an out-of-date screen when we switched to a different Amazon cluster.  This should be fixed now.  Would you mind giving it a try?
Thanks,
Tony

**Comment by MariaNattestad** [comment]
Hi Tony

It wasn't working at first, so I gave it a day, and now it's back to working! 

Thank you!
Maria
